---
- name: Converge
  hosts: all
  vars:
    node_exporter_args:
      - "--collector.arp"
      - "--collector.cpu"
    node_exporter_install_from_binary: true
    node_exporter_port: 9999
    node_exporter_version: "1.0.1"
  roles:
    - ansible-role-prometheus-node-exporter
