---
collections:
  - name: chocolatey.chocolatey
    version: 1.4.0
  - name: community.general
    version: 6.5.0

roles:
  - src: https://github.com/Ableton/ansible-role-pkg-mgr-path
    scm: git
    name: ableton.pkg_mgr_path
    version: 0.0.2
