---
collections:
  - name: chocolatey.chocolatey
    version: 1.3.1
  - name: community.docker
    version: 3.2.1
  - name: community.general
    version: 6.0.1

roles:
  - src: https://github.com/Ableton/ansible-role-pkg-mgr-path
    scm: git
    name: ableton.pkg_mgr_path
    version: 0.0.2
