---
collections:
  - name: chocolatey.chocolatey
    version: 1.5.2
  - name: community.general
    version: 10.1.0

roles:
  - src: https://github.com/Ableton/ansible-role-pkg-mgr-path
    scm: git
    name: ableton.pkg_mgr_path
    version: 0.0.3
