---
- import_tasks: "unix/install-binary.yml"
  when: node_exporter_install_from_binary and ansible_os_family != "Windows"

- import_tasks: "windows/install-binary.yml"
  when: node_exporter_install_from_binary and ansible_os_family == "Windows"

- include_tasks: "{{ ansible_os_family | lower }}\
    /install-package-{{ ansible_pkg_mgr }}.yml"
  when: not node_exporter_install_from_binary

- include_tasks: "{{ ansible_os_family | lower }}\
    /configure-service-{{ ansible_service_mgr }}.yml"
  when: ansible_os_family != "Windows"
