---
- name: Fetch node_exporter sources
  command: "go get {{ node_exporter_pkg }}"
  # On platforms like macOS, we need to make sure that /usr/local/bin is in the
  # path, which is not guaranteed to be the case even if golang has been
  # installed via homebrew.
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"

- name: Set node_exporter_path with GOPATH
  set_fact:
    node_exporter_path: "{{ ansible_env.GOPATH }}/src/{{ node_exporter_pkg }}"
  when: ansible_env.GOPATH is defined

- name: Set node_exporter_path manually
  set_fact:
    node_exporter_path: "{{ ansible_env.HOME }}/go/src/{{ node_exporter_pkg }}"
  when: ansible_env.GOPATH is not defined

- name: Make node_exporter
  command: "make -j{{ node_exporter_make_jobs }}"
  args:
    chdir: "{{ node_exporter_path }}"
    creates: "{{ node_exporter_path }}/node_exporter"
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"

- name: Set node_exporter_exe with absolute path of node_exporter
  set_fact:
    node_exporter_exe: "{{ node_exporter_path }}/node_exporter"
