---
galaxy_info:
  role_name: prometheus_node_exporter
  author: Nik Reiman
  description: Installs the Promotheus node exporter service
  company: Ableton AG

  license: BSD

  min_ansible_version: 1.2

  github_branch: master

  platforms:
    - name: Debian
      versions:
        - all
    - name: Mac OS X
      versions:
        - all
    - name: Windows
      versions:
        - 7
        - 8
        - 8.1
        - 10

  galaxy_tags: []

  dependencies: []
