---
- name: Install prometheus-node-exporter package
  become: true
  apt:
    name: prometheus-node-exporter
    state: present

- name: Set node_exporter args for apt package installation
  become: true
  copy:
    dest: "/etc/default/prometheus-node-exporter"
    content: "ARGS='{{ node_exporter_args | join(' ') }} \
      --web.listen-address=:{{ node_exporter_port }}'"
    mode: "0644"
  when: not node_exporter_install_from_binary
