---
- name: Install prometheus-node-exporter package
  become: true
  ansible.builtin.apt:
    name: prometheus-node-exporter
    install_recommends: false
    state: present

- name: Set node_exporter args for apt package installation
  become: true
  ansible.builtin.copy:
    dest: "/etc/default/prometheus-node-exporter"
    content: "ARGS='{{ node_exporter_args | join(' ') }} \
      --web.listen-address=:{{ node_exporter_port }}'"
    mode: "0644"
  when: not node_exporter_install_from_binary
