---
- name: Install prometheus-windows-exporter package
  chocolatey.chocolatey.win_chocolatey:
    name: prometheus-windows-exporter.install
    params: "/ListenPort:{{ node_exporter_port }}"
    state: present
