---
- name: Install prometheus-wmi-exporter package
  chocolatey.chocolatey.win_chocolatey:
    name: prometheus-wmi-exporter.install
    params: "/ListenPort:{{ node_exporter_port }}"
    state: present
