---
- name: Get info for the windows_exporter service
  ansible.windows.win_service_info:
    name: "windows_exporter"
  register: service_info
  ignore_errors: true
  when: windows_exporter_textfile_dir is defined

- name: Set expected_textfile_parameter fact
  ansible.builtin.set_fact:
    expected_textfile_parameter: >-
      --collector.textfile.directory {{ windows_exporter_textfile_dir }}
  when:
    - windows_exporter_textfile_dir is defined
    - service_info.exists

- name: Set windows_exporter_force_uninstall fact
  ansible.builtin.set_fact:
    windows_exporter_force_uninstall: true
  when:
    - windows_exporter_textfile_dir is defined
    - service_info.exists
    - not expected_textfile_parameter in service_info.services[0].path

- name: Uninstall windows-exporter package
  chocolatey.chocolatey.win_chocolatey:
    name: "prometheus-windows-exporter.install"
    state: absent
  when:
    - windows_exporter_force_uninstall is defined
    - windows_exporter_force_uninstall

- name: Install prometheus-windows-exporter package
  chocolatey.chocolatey.win_chocolatey:
    name: prometheus-windows-exporter.install
    params: >-
      /ListenPort:{{ node_exporter_port }}
      {{ "/TextFileDir:" + windows_exporter_textfile_dir
      if windows_exporter_textfile_dir }}
    state: present
    version: "{{ windows_exporter_version }}"

- name: Set process priority
  ansible.windows.win_regedit:
    path: "HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\
      \\Image File Execution Options\\windows_exporter.exe\\PerfOptions"
    name: "CpuPriorityClass"
    data: "{{ node_exporter_process_priority_win }}"
    type: dword
  register: win_process_priority_result

# We actually could use a handler here, except that the presence of the win_service module
# in the handler's `main.yml` file causes ansible-lint to fail, because it doesn't support
# linting Windows-specific modules.
- name: Restart windows_exporter service for Windows  # noqa: no-handler
  ansible.windows.win_service:
    name: "windows_exporter"
    state: restarted
  when: win_process_priority_result is changed
