---
- name: Set node_exporter_exe to homebrew's installation path
  set_fact:
    node_exporter_exe: "/usr/local/bin/node_exporter"

- name: Initialize fact for node_exporter extra arguments
  set_fact:
    node_exporter_args_mac: ""

- name: Build node_exporter extra arguments
  set_fact:
    node_exporter_args_mac: >
      {{ node_exporter_args_mac }}
      <string>{{ node_exporter_arg }}</string>
  with_items: "{{ node_exporter_args }}"
  loop_control:
    loop_var: node_exporter_arg

- name: Ensure LaunchDaemon plist file exists
  become: true
  template:
    src: "{{ role_path }}/templates/{{ node_exporter_ident }}.plist.j2"
    dest: "{{ node_exporter_plist }}"

- name: Load node_exporter service
  become: true
  command: "launchctl load {{ node_exporter_plist }}"
  changed_when: false
  register: node_exporter_load

- name: Check if node_exporter service is running
  become: true
  command: "launchctl list {{ node_exporter_ident }}"
  changed_when: false
  register: node_exporter_list
  failed_when: node_exporter_list.rc != 0 or '"PID" =' not in node_exporter_list.stdout
  when: "'service already loaded' not in node_exporter_load.stderr"
  delay: 1
