---
- name: Install node_exporter package
  homebrew:
    name: "node_exporter"
    state: present

- name: Set node_exporter_exe to homebrew's installation path
  set_fact:
    node_exporter_exe: "/usr/local/bin/node_exporter"

- name: Ensure LaunchDaemon plist file exists
  become: true
  template:
    src: "{{ role_path }}/files/{{ node_exporter_ident }}.plist.j2"
    dest: "{{ node_exporter_plist }}"

- name: Ensure node_exporter service is loaded
  become: true
  command: "launchctl load {{ node_exporter_plist }}"
