---
- name: Fetch node_exporter package
  command: "go get {{ node_exporter_pkg }}"
  # On macOS, we need to make sure that /usr/local/bin is in the path, which is not
  # guaranteed to be the case even if golang has been installed via homebrew.
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"

- name: Set node_exporter_path with GOPATH
  set_fact:
    node_exporter_exe: "{{ ansible_env.GOPATH }}/bin/node_exporter"
  when: ansible_env.GOPATH is defined

- name: Set node_exporter_path manually
  set_fact:
    node_exporter_exe: "{{ ansible_env.HOME }}/go/bin/node_exporter"
  when: ansible_env.GOPATH is not defined

- name: Ensure LaunchDaemon plist file exists
  become: true
  template:
    src: "{{ role_path }}/files/{{ node_exporter_ident }}.plist.j2"
    dest: "{{ node_exporter_plist }}"

- name: Ensure node_exporter service is loaded
  become: true
  shell: "launchctl load {{ node_exporter_plist }}"
