---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ansible-role-prometheus-node-exporter-install-binary-focal
    image: ubuntu:20.04
provisioner:
  name: ansible
  log: true
verifier:
  name: ansible
