---
dependency:
  name: galaxy
  options:
    force: true
driver:
  name: docker
platforms:
  - name: ansible-role-prometheus-node-exporter-install-binary-focal
    image: ubuntu:20.04
  - name: ansible-role-prometheus-node-exporter-install-binary-noble
    image: ubuntu:24.04
provisioner:
  name: ansible
  log: true
verifier:
  name: ansible
