---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ansible-role-prometheus-node-exporter-install-binary-jammy
    image: ubuntu:22.04
  - name: ansible-role-prometheus-node-exporter-install-binary-noble
    image: ubuntu:24.04
provisioner:
  name: ansible
  log: true
verifier:
  name: ansible
